const c = '/figma-assets/challenge'

/** Raster icons from Figma are often SVG text — use `.svg` so `<img>` loads correctly. */
export const challengeAssets = {
  back: `${c}/arrow-back.svg`,
  chevronDown: `${c}/chevron-down.svg`,
  leaderboard: `${c}/icon-leaderboard.svg`,
  portfolio: `${c}/icon-portfolio.svg`,
  performance: `${c}/icon-performance.svg`,
  searchActivity: `${c}/icon-search-activity.svg`,
  ellipsis: '/figma-assets/vector-ellipsis.svg',
  ellipsisHeader: `${c}/ellipsis-header.svg`,
  imageIcon: `${c}/icon-image.svg`,
  pollIcon: `${c}/icon-poll.svg`,
  investmentIcon: `${c}/icon-investment.svg`,
  plusIcon: `${c}/icon-plus.svg`,
  avatarA: `${c}/avatar-a.png`,
  avatarB: `${c}/avatar-b.png`,
  avatarC: `${c}/avatar-c.png`,
  avatarD: `${c}/avatar-d.png`,
  avatarHost: `${c}/avatar-host.png`,
  composerAvatar: `${c}/composer-avatar.png`,
  gain1: `${c}/gain-1.png`,
  gain2: `${c}/gain-2.png`,
  gain3: `${c}/gain-3.png`,
  gain4: `${c}/gain-4.png`,
  bulb: `${c}/bulb.png`,
  feedAvatar: `${c}/feed-avatar.png`,
  tsla: `${c}/tsla.png`,
  unionBadge: `${c}/union-badge.svg`,
  line23: `${c}/line23.svg`,
  line24: `${c}/line24.svg`,
  stockDown: `${c}/stock-down.svg`,
  navRing: `${c}/nav-ring.svg`,
  navInner: `${c}/nav-inner.svg`,
  dollar: `${c}/mdi-dollar.svg`,
} as const
